name: Ejecutar Script en la Nube

on:
  push:
    branches:
      - main  # Se ejecuta cuando haces push a la rama main
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar script
        run: |
          python tu_script.py

